workspace:
  path: src

pipeline:
  install:
    image: golang:1.7.3-alpine
    commands:
      - git clone https://github.com/drone/drone-hugo-theme.git themes/drone-hugo-theme

  generate:
    image: webhippie/hugo:latest
    commands:
      - hugo

  upload:
    image: plugins/s3-sync:1.1
    access: public-read
    region: us-east-1
    bucket: readme.drone.io
    source: public/
    target: /tutorials
    delete: false
    content_type:
      ".svg": image/svg+xml
    when:
      event: push
