baseurl: http://readme.drone.io/tutorials/
languageCode: en-us
title: Tutorials | Drone
theme: drone-hugo-theme

taxonomies:
  tag: tags
  label: labels

params:
  heading: Tutorials
  tagline: >
    Follow along with one of our continuous
    integration & continuous delivery tutorials.
  actions:
    create: Write a Tutorial
    search: Search Tutorials

menu:
  main:
    - name: "Documentation"
      url: "http://readme.drone.io/0.5"
      weight: -900
    - name: "Tutorials"
      url: "/"
      weight: -700
      pre: selected
    - name: "Questions"
      url: "http://readme.drone.io/questions"
      weight: -500
    # - name: "Plugins"
    #   url: "http://plugins.drone.io"
    #   weight: -300
    # - name: "Projects"
    #   url: "http://plugins.drone.io"
    #   weight: -100

defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true

languages:
  en:
    weight: 1
  fr:
    weight: 2
    heading: Tutoriels
    tagline: >
      Follow along with one of our continuous
      integration & continuous delivery tutorials.
    actions:
      create: Faire un Tutoriel
      search: Chercher les Tutoriels
    menu:
      main:
        - name: "Documentation"
        - name: "Tutoriels"
        - name: "Questions"
        - name: "Plugins"
        - name: "Projets"
  es:
    weight: 3
    menu:
      main:
        - name: "Documentación"
        - name: "Tutoriales"
        - name: "Preguntas"
        - name: "Plugins"
        - name: "Proyectos"
  pt:
    weight: 4
    menu:
      main:
        - name: "Documentação"
        - name: "Tutoriais"
        - name: "Perguntas"
        - name: "Plugins"
        - name: "Projetos"
  zh-cn:
    weight: 5
    menu:
      main:
        - name: "文档"
          url: "http://readme.drone.io/0.5"
          weight: -900
        - name: "教程"
          url: "/zh-cn/"
          weight: -800
        - name: "问题"
          url: "http://readme.drone.io/questions/zh-cn/"
          weight: -700
        # - name: "插件"
        # - name: "项目"
  zh-tw:
    weight: 6
    menu:
      main:
        - name: "文件"
          url: "http://readme.drone.io/0.5"
          weight: -900
        - name: "教學"
          url: "/zh-tw/"
          weight: -800
        - name: "問題"
          url: "http://readme.drone.io/questions/zh-tw/"
          weight: -700
        # - name: "外掛"
        # - name: "專案"
  ja:
    weight: 7
    menu:
      main:
        - name: "ドキュメント"
        - name: "チュートリアル"
        - name: "質問"
        - name: "プラグイン"
        - name: "プロジェクト"
  ru:
    weight: 8
    menu:
      main:
        - name: "Документация"
          url: "http://readme.drone.io/0.5"
          weight: -900
        - name: "Учебники"
          url: "/ru/"
          weight: -800
        - name: "Вопросы"
          url: "http://readme.drone.io/questions/ru/"
          weight: -700
        # - name: "Плагины"
        # - name: "Проекты"
  hu:
    weight: 9
    menu:
      main:
        - name: "Dokumentációt"
        - name: "Oktatóanyagok"
        - name: "Kérdéseket"
        - name: "Dugó"
        - name: "Projektek"
